### ISSUE TITLE
Firefox Support?

### ISSUE THREAD

**Issue by ikzk** [FooSoft/yomichan-chrome#10]
I just saw https://github.com/FooSoft/yomichan-chrome/pull/7 which seems to be something related to the firefox support. Is there any plan for firefox? It will be great to have this on firefox.

**Comment by FooSoft** [comment]
Firefox can be made to work very little effort, but the options page would have to be reworked. There will be ports for various browsers as soon as I get the feature set for the original Chrome release nailed down.

**Comment by ikzk** [comment]
@FooSoft  Great! Looking forward to it!
