### ISSUE TITLE
[feature request] mouse over select whole words(in english) instead of character

### ISSUE THREAD

**Issue by ninja33** [FooSoft/yomichan-chrome#11]
Hi @FooSoft :
Just happened to know such wonderful chrome extension for foreign language studying.

### User Experience:
I am English learner (as Chinese native speaker). I followed IR (incremental reading) practice to write down new English word with sentence as context while visiting news webpage like BBC, CNN. usually I will manually input these information into Anki for reviewing later. So, you can not imagine the stunning feeling :+1: I had when I first time knew this tool. It saved me lots of time to copy and paste, and just focus on what they called another IR(immersion reading). after I finished reading, all cards were there already in Anki! 

### Personal Practice:
so, I want to use and convert it in my Learning English process. By ignoring extra Japanese learning module, like Kanji-dict, Rule, in your code. the edict part, including [express,reading,tags, glossary], can be perfectly  mapped to [word, pronunciation, tags(part of speech) and definitions] and meet my requirement.

### My Problem:
the only problem is that Japanese and Chinese is character based language, but English is word based. so, when I tried to mouse over select English word, it only workable when I put mouse point exactly above the first letter of that word. by the way, the "Scan length" in option is also calculated by Japanese character/English letter.

I tried to fork this project and made some changes on `client.js` and `source-range.js`, it's kinds of workable by detecting white space between words , but it not sounds like more general solution with well behavior coding skill (I never wrote JS before). so, just wondering if there would have more general option as listed below, 

### Feature Requested:

1. add one option item in back-end option page to indicate character or word based language. 
2. based on above item 1, can mouse over select one by one character or word by word. of course, the scan length also could be character or word based.

### Other Suggestions (or imagination):

1. `[express, reading, tag, glossy and sentence]` with Anki connect is core and general function for all language studying, so, it could be as basic package for all language learner. I have used readlang and LWT (Leaning with Text), all those tools need extra effort to import text and integrate with anki. Yomichan is the best without any extra effort. just hope it can be used by more peoples. as for other module, like Kanji, Rule, Katakana, Hiragana(and wonderful! de-inflection function), maybe it can be de-coupled from core function as addons.
2. when build my English-Chinese dict by following your edict format, noticed you already dumped these dict data in sqlite format in `compile.py`. As you may know json data is very memory consumed in Chrome(the extension itself sized up to 45M also, and Chrome memory allocation can be over 1G) so, by leveraging anki connect as a bridge to access local sqlite dict db, it may save both extension size and Chrome memory. Also, it also could be configurable in the future to change dict(not embedded in extension itself) by following your standard dict format.
3. just like Anki addon "awesome TTS", don't know if it's possible that audio link can be pre-configured as service provider and select-able. understood it's not just as simple as usual query link, like `http://www.online-dict/?q={word}`, but if it could be extended by coding level to provide more online audio service provider in progress, it's also highly appreciated.

**Comment by FooSoft** [comment]
Thanks for checking out Yomichan! 

I think that selection in an word-based language is an easier problem to solve than in a character-based language like Chinese or Japanese. If you are trying to add this functionality, you wouldn't really even have to worry about scan length; just search forwards and backwards until you find a space! The whole reason for the scan length was that without spaces it is really difficult to determine where to stop looking.

I think at the point where we start supporting multiple languages, it may make sense to have multiple plugins (based on a reusable core). Dictionary files can be large and per-language configuration options might be confusing to users who only care about one language (for example, seeing references to "hiragana" might be super confusing to users trying to learn English). 

Regarding the dictionary format, I completely agree with you that JSON is less than ideal. The problem is that there does not appear to be a way to just use an sqlite database from within the Chrome extension environment. If I am wrong, and you know of a way that this can be done, I would love to hear it  : )

**Comment by ninja33** [comment]
Yes, agree your point to make thing simple to have multiple plugin built by reusable core lib.

For the db issue, Chrome itself may not have this capability, but Python has. 

As mentioned in above suggestion point 2: **"leveraging Anki connect as bridge"**, noticed you already had an anki_api in `bg/options-form.js` called `api_getModelFieldNames()` which send a model name to Anki and get a fields list as feedback. so, similarly, it can be changed to `api_getTermDefinition()` by sending term text and getting a list of  [e,r,t,...g] which queried from local sqlite by python as feedback. (because Anki itself used sqlite as internal db, so user even do not need import any other python module). The performance should not be the issue, as you know, lots of online dictionary which has words mouse over/selection instant translation feature. They even send word to server back and forth through internet. by reusing "anki connect" interface, it's on local host.

Except it can reduce extension size and Chrome memory allocation, the advantage is that community can follow your standard dictionary and db format to develop, extend & exchange their own dictionary. the only shortage is Chrome extension is no longer an "ready to go" and all in one package, but it can be avoided by shipping a very basic and small size dictionary in Chrome extension as default, just like what you did in Yomichan (with edict as default dictionary)

**Comment by FooSoft** [comment]
Ah, but the problem is that I would like for Yomichan on Chrome to be able to function even if Anki is not running. Another option would be to run a deinflect/dictionary sever on my host and resolve lookup queries... unfortunately this has serious privacy implications.

**Comment by ninja33** [comment]
with or without anki, that's not the problem. host a tiny http server by using python or other way is easy.  just as you created a tiny socket server to response JSON data from anki connect.

the point is the dictionary service must be located locally to provide customized dictionary. otherwise, if you run dictionary server on your host and open XHR request to that server, that's no difference between this solution and other online dictionary.

anyway, thanks your feedback.

I got another problem because of current character based solution. if I mouse over "your", but if I have both definition of "you" and "your" in my English_to_Chinese dictionary, the word "you" also will appear in popup window,   need more study to resolve this problem :cry:

**Comment by FooSoft** [comment]
You are 100% right about running a local server being a fast, efficient and easy thing to do. That being said, you have to consider the user experience; for us, running python is trivial... for other users it can be a challenge to get things running (especially on Windows systems). I can already see people installing the wrong version, etc. 

There is of course the option to create platform specific executables (via py2exe, or if I were to actually do this, just use Go or something), but this also raises trust issues. I think it might be difficult to convince people to run some random executable from the net for a chrome extension. For custom dictionaries, this might be the only option; however, I think that we still need to provide the slow, bloated JSON option just for its ease of use. It might be also possible to do something with file upload control, and storing dictionary data in localstorage... This requires more investigating.

For looking up English, you should just tokenize based on spaces, and it should be all good I think. Just make the range code to seek ahead to the first space and stop. I'm not sure what you are using for deinflection, but the Japanese approach of walking backwards one character at a time will have to be changed for English.

**Comment by ninja33** [comment]
Yes, that's too complicated for chrome extension end users. 

you know, I am anki user first, and then found a perfect tool to integrate with anki. from my point of view, that's why I am always thinking it's just one step forward from anki connect. because for developer, that's just one more api in ankiconnect.py, for anki connect user, the python version and sqlite access is not problem because anki was there running already to provide environment. 

so, seems local dictionary service can only be an option(let's call it anki dictionary) for those anki users who already enabled anki connect feature. hemm, sounds it's a rarely used feature and not such straight forward for most people. let's just forget about it.

---

for de-inflection, it's problem in language as English. but it's also not problem if I have a right dictionary. in English, you know, like past tense [verb]ed, you just can not simply de-inflect and treat it as verb, sometimes, [verb]ed is also an adj. ; and [verb]ing can be a noun. so, it's complicated. 

In some dictionaries, it will list the stem word with whole word family. I found a very useful feature in your dictionary structure -- indices. it's one to many mapping can be used to cross reference for stem word within same word family, so I just list them all with stem and give choice to end users which form of that word they want to select in current context.

**Comment by FooSoft** [comment]
I spent some time looking around to see what could be a better solution, and it seems like IndexedDB might be the way to go. It's supported in all browsers, and even though it is "temporary" storage, in practice it seems like it is pretty permanent. When the user runs the extension for the first time, it can dump the JSON dictionaries into the database and use it from that point on. New dictionaries could be imported through a file upload dialog in options.

**Comment by ninja33** [comment]
Great, and seems there is no storage limitation in current Chrome/Firefox implementation.

My adaption version of Yomichan E2C(English to Chinese) was almost completed, it's pretty well with a little bit de-inflection issue. as  you highlighted, it should be a totally different extension for different language. so, seems no chance to pull request here from my fork. I put the unpacked extension in an English learner group and asked them help test. 

May I ask your permission to submit packed extension to Chrome store in the near feature.
It included a credit link to Yomichan homepage at the end of back-end option page.

one more thing, since version 0.94, I found dictionary format changed a lot. because dictionary file itself is in JSON format which means it actually is a javascript object. So `dictionary.js` in back-end is heavily coupled by this object structure. that's another reason I can't keep sync and pulling remote repo from upstream since v0.93 (my fork point)

anyway, thank you  so much for this great project. we can close this issue if no more further discussion.

**Comment by FooSoft** [comment]
You can definitely put your extension up in the app store, but I request that you call it something entirely different (don't have Yomichan in the name). This is of benefit for both projects since it avoids confusion about which version the user is getting. Internally, of course, I don't mind references to Yomichan, etc. The name Yomichan itself, as you probably realized, is something that points toward it being a tool for learning Japanese.

**Comment by FooSoft** [comment]
Closing out old issues
