### ISSUE TITLE
Improvement to ordering of looked up words

### ISSUE THREAD

**Issue by nevil** [FooSoft/yomichan-chrome#12]
Hi,

This is a great extension for chrome. Thank you very much for providing it!
This is a very specific request but possibly it is a larger issue related to the dictionary.

I have this sentence: "キーイメージサイズのサムネ画像を取得し、取得後画像入れ替え。"
When looking up "取得" Yomichan suggests "とりえ" as first and "しゅとく" as second result.

But I believe it should be "しゅとく" and that "とりえ" would normally be written as 取り得, though I am likely wrong :-)

Making a long story short, the request is to somehow improve the listed order of suggestions to match the most common reading of the word.

**Comment by FooSoft** [comment]
Good catch. The words tagged `P` sort before ones that aren't, but in this case the とりえ is tagged `iK` for "irregular Kanji usage". I'll just penalize the sort score for having this tag to make it go further down on the list.

**Comment by h-anders-unext** [comment]
Thanks for the quick response!
Great that the dataset already has metadata that can be used. 👍 
I think this will be a good enhancement to Yomichan.

**Comment by nevil** [comment]
Thanks for the quick response!
Great that the dataset already has metadata that can be used. 👍 
I think this will be a good enhancement to Yomichan.

**Comment by h-anders-unext** [comment]
@FooSoft 
The change seems to be working fine.

Thanks!

**Comment by nevil** [comment]
@FooSoft 
The change seems to be working fine.

Thanks!
