### ISSUE TITLE
yomichan doesn't work on local pages (file:///)

### ISSUE THREAD

**Issue by eubr** [FooSoft/yomichan-chrome#17]
Hi!

Steps to reproduce:

go to http://www.asahi.com/ and press shift over various words; yomichan works as expected
press ctrl + s to save the page locally
open the saved page, press shift over various words, yomichan doesn't show anything

Is this expected? Let me know if you need any additional detail.

**Comment by FooSoft** [comment]
This actually works, but you have to enable local file access first. In Chrome, go to the extensions page (chrome://extensions/) and check `Allow access to file URLs` for Yomichan.

**Comment by eubr** [comment]
Thanks.
