### ISSUE TITLE
[feature request]　hover to activate

### ISSUE THREAD

**Issue by gajewsk2** [FooSoft/yomichan-chrome#18]
Allow for a setting that automatically shows word meanings on hover without the need to hold shift+hover. This would allow for the rikai-like functionality most are already used to, as well as give support to devices without mouse support (touch devices, MS surfaces, etc.).

Envisioning this as a toggleable setting.

**Comment by FooSoft** [comment]
How do you see being able to move the mouse over to the definition window without triggering new lookups from taking place while hovering over other text?

**Comment by gajewsk2** [comment]
Envisioning the behavior as, when the box is open nothing under it should be scanned, user can click outside the box to close it, as it currently behaves or scan another word and the box will move to that location. Basically, the same behavior as rikai, but if you want to close the box, you manually have to by tapping/clicking outside of it.

**Comment by gajewsk2** [comment]
The feature is very nice! But it seems to break hotkeys like ctrl-c. So if the word is highlighted, you press ctrl, it looses focus. Is that fixable?

**Comment by FooSoft** [comment]
It's fixed :+1:

**Comment by gajewsk2** [comment]
Awesome! Wondering if it would be possible to disable the feature when you are holding a click, eg highlighting text manually. For instance, say there's a phrase you want to search for on Google, real life example: 青血のハグルマ. I had to disable yomichrome to highlight this.

Alternatively, there could be a button to disable the feature, like holding shift to disable the auto function. At that point this is a full inverse of the built in yomichrome functionality which is interesting. I'd say I'm partial to just disabling on click holds though.

Anyways, `hover to activate` has replaced rikai-addons at this point, so thanks for the hard work, I use this daily.
