### ISSUE TITLE
Seemingly doesn't work on Facebook

### ISSUE THREAD

**Issue by denyeo** [FooSoft/yomichan-chrome#19]
Yomichan doesn't seem to work on posts on Facebook (`Shift` + mouseover) for me, does it work for anyone else? Not sure if it's because Facebook uses some funky CSS rules, or catches the `Shift` key or something. Is there a generalisable solution?

**Comment by FooSoft** [comment]
I don't have a Facebook account, could you save the page in question (or a portion of it), ZIP it (including all of the referenced resource files) and send it to alex@foosoft.net? I can probably figure out what's up if I get a local repro.

**Comment by denyeo** [comment]
Strange, it's working for me now. Must have been a temporary issue with my system yesterday. Sorry to bother!

**Comment by FooSoft** [comment]
No problem, reopen this if you have issues again
