### ISSUE TITLE
Unable to connect to plugin alert

### ISSUE THREAD

**Issue by gajewsk2** [FooSoft/yomichan-chrome#22]
Alerts are bad. I keep getting them from this plugin when I don't have ankiconnect started, even though I have it selected in my settings. Any page I go to now throws alerts.

**Comment by FooSoft** [comment]
This particular alert is pretty lame, so it was removed. I'm open to discussion and/or pull requests on better ways to display errors.

**Comment by gajewsk2** [comment]
I like that it is displayed in the options. I think thats more friendly than a console log or alert.
