### ISSUE TITLE
Priority tag intersection

### ISSUE THREAD

**Issue by HelenFoster** [FooSoft/yomichan-chrome#24]
Hi, in JMDICT the priority tags are attached to kanji and reading elements separately "because on occasions a priority is only associated with a particular kanji/reading pair". It seems Yomichan is showing a priority tag for a kanji/reading pair if either the kanji or the reading has that tag. It would be more accurate to JMDICT's intention to show the tag if both the kanji and the reading have it.

My main use case here is looking up a priority kanji word which has one priority reading and at least one non-priority reading, and trying to decide which reading is more likely. (At the moment they all appear as priority.)

Using 0.997 on Fedora.

**Comment by FooSoft** [comment]
This was fixed at some point... just forgot to close out this bug.
