### ISSUE TITLE
Distinguish "Anki card already added" from "no response"

### ISSUE THREAD

**Issue by HelenFoster** [FooSoft/yomichan-chrome#25]
Hi, currently the "add to Anki" icons look the same whether the card is already added, or if there is no response from Anki yet. This can be confusing when skimming over words quickly. I would like to suggest using a different icon for the two situations.

**Comment by FooSoft** [comment]
Maybe I'll add one of those AJAX spinner animation things like on the options page.

**Comment by HelenFoster** [comment]
Animation might be annoying if I'm using Yomichan when Anki is closed.

**Comment by FooSoft** [comment]
Ah, I misread, I thought you were talking about the delay between clicking the button and the card being added. For this particular case, it might make sense just to hide the Anki buttons entirely until a response comes back.

**Comment by HelenFoster** [comment]
I think you're right - hide the buttons for "don't know whether we can add the card" and animation for "working on adding it". (With an equal-sized placeholder for the hidden buttons so things don't jump around when the response comes.)
