### ISSUE TITLE
Keep AnkiConnect settings when disabled

### ISSUE THREAD

**Issue by HelenFoster** [FooSoft/yomichan-chrome#27]
Hi, if I change the connection method from AnkiConnect to Disabled and back to AnkiConnect, it forgets all the AnkiConnect settings. I would expect them to come back how they were before. (Testing with 1.0.1 on Windows.)

**Comment by FooSoft** [comment]
The problem with keeping settings is that fields which should seemingly have the same values end up being different based on what connection method you are using. You can see this by viewing which models are shown when using the AnkiWeb interface vs. the AnkiConnect interface. They should be the same (the fields are indeed the same), but the model names are different. Not sure what can be done about that... but yes, I agree, having to re-enter all your info every time you switch methods can be annoying.

**Comment by HelenFoster** [comment]
If the settings have different values depending on the connection method, would it make more sense to use different settings internally?
